import json
import os
from pathlib import Path
from pprint import pformat

from dotenv import load_dotenv
from openai import OpenAI

from config import ROOT_DIR, load_knowledge_base


OUTPUT_JSON = ROOT_DIR / "data" / "generated_qa_pairs.json"
OUTPUT_PY = ROOT_DIR / "qa_pairs.py"


def get_client() -> OpenAI:
    load_dotenv(ROOT_DIR / ".env")
    api_key = os.getenv("SHOPAIKEY_API_KEY")
    if not api_key:
        raise RuntimeError(
            "SHOPAIKEY_API_KEY is missing. Add it to .env, save the file, then rerun this script."
        )
    return OpenAI(
        api_key=api_key,
        base_url=os.getenv("SHOPAIKEY_BASE_URL", "https://api.shopaikey.com/v1"),
    )


def build_prompt(knowledge: str) -> list[dict]:
    system = (
        "You generate high-quality RAG evaluation data. "
        "Return only valid JSON. Do not wrap the JSON in markdown."
    )
    user = f"""
Create exactly 50 question-answer pairs for a RAG lab using the VinFast VF 3 knowledge base below.

Rules:
- Questions must be answerable from the knowledge base only.
- Mix warranty, battery, charging, dimensions, safety, service, and feature questions.
- Keep questions natural and concise.
- Each reference answer must be a complete factual answer with numbers, units, and conditions when available.
- Do not invent facts not present in the knowledge base.
- Output JSON with this exact shape:
{{
  "qa_pairs": [
    {{"question": "...", "reference": "..."}}
  ]
}}

Knowledge base:
{knowledge}
""".strip()
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


def call_model(client: OpenAI, knowledge: str) -> list[dict]:
    model = os.getenv("QA_GENERATOR_MODEL", "gpt-4o-mini")
    response = client.chat.completions.create(
        model=model,
        messages=build_prompt(knowledge),
        temperature=0.2,
        response_format={"type": "json_object"},
    )
    content = response.choices[0].message.content
    payload = json.loads(content)
    qa_pairs = payload.get("qa_pairs", [])
    if len(qa_pairs) != 50:
        raise ValueError(f"Expected 50 qa_pairs, got {len(qa_pairs)}")
    for i, item in enumerate(qa_pairs, 1):
        if not item.get("question") or not item.get("reference"):
            raise ValueError(f"Invalid QA pair at index {i}: {item}")
    return qa_pairs


def write_outputs(qa_pairs: list[dict]) -> None:
    OUTPUT_JSON.parent.mkdir(exist_ok=True)
    OUTPUT_JSON.write_text(
        json.dumps({"qa_pairs": qa_pairs}, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    py_text = (
        "# Generated by generate_qa_pairs.py using gpt-4o-mini via ShopAIKey.\n"
        f"QA_PAIRS = {pformat(qa_pairs, width=100, sort_dicts=False)}\n\n"
        'SAMPLE_QUESTIONS = [item["question"] for item in QA_PAIRS]\n'
    )
    OUTPUT_PY.write_text(py_text, encoding="utf-8")


def main() -> None:
    knowledge = load_knowledge_base()
    client = get_client()
    qa_pairs = call_model(client, knowledge)
    write_outputs(qa_pairs)
    print(f"Generated {len(qa_pairs)} QA pairs")
    print(f"Saved {OUTPUT_JSON}")
    print(f"Updated {OUTPUT_PY}")


if __name__ == "__main__":
    main()
